name: research-sync

on:
  # Runs when anything in research/ or the research log changes,
  # and can also be triggered manually.
  push:
    branches: [main]
    paths:
      - 'research/**'
      - 'meta/research_log.md'
  workflow_dispatch:

# Default token is read‑only; we push with our fine‑grained PAT in secrets.DR_PAT
permissions:
  contents: read

env:
  TARGET_BRANCH: DeepResearch.AI.AdelaideCannabisCultivationVariant

jobs:
  sync-research:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Git identity from secrets
        run: |
          git config --global user.name  "${{ secrets.GIT_NAME }}"
          git config --global user.email "${{ secrets.GIT_EMAIL }}"

      - name: Debug — show PAT length (will not print the token itself)
        run: echo "DR_PAT length: ${#{{ secrets.DR_PAT }}}"

      # ------------------------------------------------------------
      #  Add or update your indexing script here if needed, e.g.:
      #  python scripts/build_index.py
      # ------------------------------------------------------------

      - name: Stage research index and log
        run: |
          git add research/index.md meta/research_log.md || true

      - name: Commit & Push
        env:
          GH_TOKEN: ${{ secrets.DR_PAT }}
        run: |
          if git diff --cached --quiet; then
            echo "No changes to commit."
            exit 0
          fi
          git commit -m "CI: auto-index research on $(date -u +'%Y-%m-%d %H:%M UTC')"
          git push https://$GH_TOKEN@github.com/${{ github.repository }} HEAD:$TARGET_BRANCH
